name: flutter_proyecto
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

assets:
  - lib/icons/

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.35.0
  http: ^0.13.3
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
